server:
  port: 2602

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: gamers-gateway
  cloud:
    gateway:
      routes:
        - id: dynamics-service
          uri: localhost:2603
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: true

  redis:
    host: localhost
    port: 6379
    password: 123456
