server:
  port: 2602

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  sensitive-headers:
  routes:
    dynamics:
      path: /dynamics/**
      serviceId: gamers-dynamic
      strip-prefix: false
    accounts:
      path: /accounts/**
      url: gamers-accounts
      strip-prefix: false
    login:
      path: /login/**
      serviceId: gamers-accounts
      strip-prefix: false

  redis:
    host: localhost
    port: 6379
    password: 123456
