server:
  port: 2602

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  sensitive-headers:
  routes:
    accounts:
      path: /dynamics/**
      url: http://localhost:18082
      strip-prefix: fales

  redis:
    host: localhost
    port: 6379
    password: 123456
