server:
  port: 2602

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  application:
    name: gamers-gateway
  cloud:
    gateway:
      routes:
        - id: user-dynamic-service
          uri: https://www.baidu.com
          predicates:
            - Path=/dynamics
      discovery:
        locator:
          enabled: true

  redis:
    host: localhost
    port: 6379
